app/routes.py
import os
import re
import typing as t

import peewee
from flask import Blueprint, abort, render_template, request, send_from_directory
from playhouse.flask_utils import PaginatedQuery

from .app import APPPATH
from .modeles import Author, FTSMonography, Inventory, Monography, Subtype, Type

RESULT_PAR_PAGES = 5

main = Blueprint("main", __name__, url_prefix="/")


@main.route("/")
def home() -> t.Text:
    """Displays the home page"""
    corpus = Monography.select().order_by(Monography.id)
    return render_template("home.html", corpus=corpus, fluid=True)


@main.route("/monographies")
def monographies() -> t.Text:
    """Displays the list of monographies"""
    corpus = Monography.select().order_by(Monography.id)
    return render_template("corpus.html", corpus=corpus, title="Les monographies")


@main.route("/monographie/<string:slug>")
def txt_mono(slug: str) -> t.Text:
    """Displays the monography"""
    try:
        monography = Monography.get(Monography.slug == slug)
    except Monography.DoesNotExist:
        abort(404)

    prev_monography = Monography.get_or_none(Monography.id == monography.id - 1)
    next_monography = Monography.get_or_none(Monography.id == monography.id + 1)

    content = monography.content.replace(
        '<div id="toc"><h3>Sommaire</h3></div>', '<div id="toc"><h3>Sommaire</h3>' + monography.toc + "</div>"
    )
    return render_template(
        "mono.html",
        monography=monography,
        content=content,
        prev=prev_monography,
        next=next_monography,
        title=monography.short_title,
    )


@main.route("/monographie/<string:slug>/download/xml")
def download_xml(slug: str) -> t.Text:
    """Downloads a monography as XML"""
    try:
        monography = Monography.get(Monography.slug == slug)
    except Monography.DoesNotExist:
        abort(404)

    return send_from_directory(
        os.path.join(APPPATH, "static", "xml"),
        monography.filename,
        as_attachment=True,
        download_name=f"{monography.public_id}-{monography.short_title}.xml",
    )


@main.route("/monographie/<string:slug>/download/pdf")
def download_pdf(slug: str) -> t.Text:
    """Downloads a monography as PDF"""
    try:
        monography = Monography.get(Monography.slug == slug)
    except Monography.DoesNotExist:
        abort(404)

    return send_from_directory(
        os.path.join(APPPATH, "static", "pdf"),
        monography.filename.replace(".xml", ".pdf"),
        as_attachment=True,
        download_name=f"{monography.public_id}-{monography.short_title}.pdf",
    )


@main.route("/simple-search")
def search() -> t.Text:
    """Displays the search page."""
    subtype_tble = Subtype.select(Subtype, Type).join(Type).order_by(Subtype.label)
    subtypes: t.Dict[str, t.List[Subtype]] = {}
    for subtype in subtype_tble:
        if subtype.type.label not in subtypes:
            subtypes[subtype.type.label] = []
        subtypes[subtype.type.label].append(subtype)
    return render_template("search-simple.html", subtypes=subtypes, title="Recherche avancée")


@main.route("/simple-search/<string:where>")
def results(where: str) -> t.Text:
    """Displays the search results page."""
    term = request.args.get("term")
    if not term:
        abort(404)

    try:
        type = Type.get(Type.label == where)
        subtype = Subtype.get(Subtype.id == term)
    except (Type.DoesNotExist, Subtype.DoesNotExist):
        abort(404)

    if subtype.type != type:
        # Sous-type n'appartient pas au type
        abort(404)

    query = (
        Inventory.select(Inventory, Monography)
        .join(Monography)
        .where(Inventory.type == type, Inventory.subtype == term)
        .order_by(Inventory.monography)
    )

    paginated_query = PaginatedQuery(
        query,
        paginate_by=RESULT_PAR_PAGES,
    )
    count = query.count()

    return render_template(
        "results-simple.html",
        where=where,
        term=term,
        type=type,
        subtype=subtype,
        results=paginated_query,
        count=count,
        title=f'{count} résultats de la recherche pour "{subtype.label}" dans les {type.nice_label}',
    )


@main.route("/search")
def searchfts() -> t.Text:
    """Displays the full-text search results"""
    term = request.args.get("term")
    if not term:
        return render_template("search-full.html", title="Recherche")

    if "'" in term and '"' not in term:
        # Unquoted single quote
        # Not supported by FTS5, would generate a OperationError: fts5: syntax error near "'"

        # So we quote the nearest word that has a single quote
        # This will handle most of the simple cases
        term = re.sub(r"(\w+'\w+)", r'"\1"', term)

    if '"' in term and term.count('"') % 2 == 1:
        # There is an unbalanced number of quotes, so we try to fix that by adding one at the beginning or end
        # This should fix most of the simple cases
        if term.endswith('"'):
            term = '"' + term
        else:
            term = term + '"'

    query = (
        Monography.select(
            Monography,
            FTSMonography.rank().alias("score"),
            FTSMonography.title.highlight("<mark>", "</mark>").alias("hi_title"),
            FTSMonography.content.snippet("<mark>", "</mark>", max_tokens=64).alias("hi_content"),
        )
        .join(FTSMonography, on=(Monography.id == FTSMonography.rowid))
        .where(FTSMonography.match(term))
        .order_by(FTSMonography.bm25())
    )

    paginated_query = PaginatedQuery(
        query,
        paginate_by=RESULT_PAR_PAGES,
    )
    try:
        count = query.count()
    except peewee.OperationalError as e:
        # Malformed term ?
        return render_template(
            "search-full.html",
            error=str(e),
            term=term,
            title="Recherche",
        )

    return render_template(
        "results-full.html",
        results=paginated_query,
        count=count,
        term=term,
        title=f"{count} résultats de la recherche pour {term}",
    )


@main.route("/authors")
def authors() -> t.Text:
    """Displays the list of authors and their monographies"""
    authors = Author.select().order_by(Author.lastname)
    return render_template("authors.html", authors=authors, title="Les enquêteurs")


@main.route("/workers")
def workers() -> t.Text:
    """Displays the list of workers for each monography"""
    corpus = Monography.select().order_by(Monography.id)
    return render_template("workers.html", corpus=corpus, title="Index des ouvriers")


@main.route("/workers_old")
def workers_old() -> t.Text:
    """Displays the list of workers for each monography"""
    corpus = Monography.select().order_by(Monography.id)
    return render_template("workers_old.html", corpus=corpus, title="Index des ouvriers")


@main.route("/monographie/<string:slug>/workers")
def monography_workers(slug: str) -> t.Text:
    """Displays the list of workers for one monography"""
    try:
        monography = Monography.get(Monography.slug == slug)
    except Monography.DoesNotExist:
        abort(404)

    return render_template(
        "workers.html", corpus=[monography], title="Index des ouvriers pour " + monography.short_title
    )


@main.route("/about")
def about() -> t.Text:
    """Displays the About page"""
    return render_template("about.html", title="À propos")


@main.route("/contact")
def contact() -> t.Text:
    """Displays the Contact page"""
    return render_template("contact.html", title="Contact")


@main.route("/termsofservice")
def terms() -> t.Text:
    """Displaysthe T&C page."""
    return render_template("terms.html", title="Mentions légales")

app/templates/conteneur.html
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1">

		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>
			{% if title %}{{ title }} - {% endif %}
		    Ouvriers des deux mondes
		</title>
		<meta name="author" content="CNRS Centre de recherches historiques">
		<meta name="application-name" content="Les Ouvriers des deux mondes">
		{% include "partials.html" %}
		{% block head %}{% endblock %}
		<!-- Matomo -->
		<script>
  			var _paq = window._paq = window._paq || [];
  			/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  			_paq.push(['trackPageView']);
  			_paq.push(['enableLinkTracking']);
  			(function() {
    			var u="https://analyseweb.huma-num.fr/";
    			_paq.push(['setTrackerUrl', u+'piwik.php']);
    			_paq.push(['setSiteId', '455']);
    			var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    			g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  			})();
		</script>
		<!-- End Matomo Code -->
	</head>
	<body>
		<div>
			<div>
        <div class="image-container">
            <a href="{{ url_for('main.home') }}">
                <img src="{{ url_for('static', filename='img/oddm_banniere.jpg') }}" alt="image"/>
                <div class="overlay-text josefin-semibold-ita">
                    <p>Ouvriers des</p>
                    <p>deux mondes</p>
                </div>
            </a>
        </div>
        <header class="sticky-top header-navbar">
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <button class="navbar-toggler navbar-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Basculer la navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent" style="text-transform: uppercase;">
                <ul class="navbar-nav mx-auto justify-content-center mb-2 mb-lg-0">
                    <li class="nav-item josefin-semibold-lightita"><a class="nav-link" href="{{ url_for('main.home') }}" title="Accueil">Accueil</a></li>
                    <li class="nav-item nav-link josefin-semibold-lightita">/</li>
                    <li class="nav-item josefin-semibold-lightita"><a class="nav-link" href="{{ url_for('main.about') }}" title="À propos de ce site">Présentation</a></li>
                    <li class="nav-item nav-link josefin-semibold-lightita">/</li>
                    <li class="nav-item josefin-semibold-lightita"><a class="nav-link" href="{{ url_for('main.monographies') }}" title="Liste des monographies">Enquêtes</a></li>
                    <li class="nav-item nav-link josefin-semibold-lightita">/</li>
                    <li class="nav-item josefin-semibold-lightita"><a class="nav-link" href="{{ url_for('main.authors') }}" title="Liste des enquêteurs">Enquêteurs</a></li>
                    <li class="nav-item nav-link josefin-semibold-lightita">/</li>
                    <li class="nav-item josefin-semibold-lightita"><a class="nav-link" href="{{ url_for('main.workers') }}" title="Liste des ouvriers">Enquêtés</a></li>
                    <li class="nav-item nav-link josefin-semibold-lightita">/</li>
                    <li class="nav-item josefin-semibold-lightita"><a class="nav-link" href="{{ url_for('main.search') }}" title="Rechercher dans les descriptions">Recherche</a></li>
                </ul>
                <!--<form class="d-flex" action="{{ url_for('main.searchfts') }}" method="GET">
                    <input class="form-control me-2" type="search" placeholder="Rechercher" aria-label="Rechercher" name="term">
                    <button class="btn btn-outline-success" type="submit" title="Recherche dans toutes les monographies">Rechercher</button>
                </form>-->
            </div>
        </div>
    </nav>
</header>

		<div class="container{% if fluid %}-fluid mt-0 mb-0{% endif %} text-justify josefin-sans-text" id="main-div">
			{% block corps %}{% endblock %}
		</div>
		<footer class="footer text-center text-lg-start"  style="border-top: 1px solid #303030;  margin: 1em auto 0 auto; width: 100%;">
            <section class="" style="padding: 1%;">
                <div class="container text-center text-md-start mt-5 josefin-sans-text">
                    <div class="row">
                        <div class="col mx-auto mb-4">
                            <h6 class="josefin-semibold-footer">Ouvriers des deux mondes</h6>
                            <p>Édition numérique de la collection <em>Les Ouvriers des deux mondes</em>.</p>
                            <p style="font-size: 12pt;">Application développée par le <a href="http://crh.ehess.fr/" title="Centre de recherches historiques" style="color: inherit !important;">Centre de recherches historiques</a>, avec le soutien de l'<a href="https://anr.fr/" title="Agence nationale de la recherche" style="color: inherit !important;">Agence nationale de la recherche</a>, d'<a href="https://almanach.inria.fr/" title="ALMAnaCH" style="color: inherit !important;">ALMAnaCH</a> et du <a href="https://www.cmh.ens.fr/" title="Centre Maurice Halbwachs" style="color: inherit !important;">Centre Maurice Halbwachs</a>. Dépôt des données: <a href="https://nakala.fr/collection/10.34847/nkl.d3b3een3" title="Dépôt Nakala" style="color: inherit !important;" target="_blank">10.34847/nkl.d3b3een3</a>.</p>
                            <p style="font-size: 10pt;">
                                <span class="link-border-dotted"> <a href="{{ url_for('main.about') }}" title="À propos de ce site">À propos</a> </span> / <span class="link-border-dotted">
                                <a href="{{ url_for('main.terms') }}" title="Mentions légales de ce site">Mentions légales</a>
                                </span> / <span class="link-border-dotted">
                                <a href="{{ url_for('main.contact') }}" title="Contacter les auteurs du site">Contact</a>
                                </span> / <span class="link-border-dotted">
                                <a href="https://www.huma-num.fr/" title="Huma-Num">IR* Huma-Num</a>
                                </span> / <span class="link-border-dotted"><a href="https://www.etalab.gouv.fr/licence-ouverte-open-licence" target="_blank" title="Licence ouverte ETALAB 2.0">Licence Etalab 2.0</a></span>
                            </p>
                        </div>
                        <div class="col d-flex align-items-center">
                            <div class="container text-center">
                                <div class="row">
                                    <div class="col" style="margin: auto;">
                                        <a href="https://anr.fr/fr/investissements-davenir/les-investissements-davenir/" target="_blank" title="ANR Investissements d'avenir">
                                        	<img style="width: 40%; height: auto;" src="{{ url_for('static', filename='img/investir_avenir.png') }}" alt="ANR Investissements d'avenir"/>
                                        </a>
                                    </div>
                                    <div class="col" style="margin: auto;">
                                        <a href="https://www.cnrs.fr/" target="_blank" title="CNRS">
                                        	<img src="{{ url_for('static', filename='img/cnrs-logo.png') }}" alt="CNRS" width="42%" height="auto" />
                                        </a>
                                    </div>
                                    <div class="col" style="margin: auto;">
                                        <a href="https://www.ehess.fr/" target="_blank" title="EHESS">
                                        	<img src="{{ url_for('static', filename='img/ehess-logo.png') }}" alt="EHESS"/>
                                        </a>
                                    </div>
                                </div>
                                <div class="row" style="padding-top: 3%; margin: auto;">
                                    <div class="col" style="margin: auto;">
                                        <a href="https://www.inria.fr/" target="_blank" title="INRIA">
                                        	<img style="width: 50%; height: auto;" src="{{ url_for('static', filename='img/inria-logo.png') }}" alt="INRIA"/>
                                        </a>
                                    </div>
                                    <div class="col" style="padding-top: 3%; margin: auto;">
                                        <a href="https://www.inrae.fr/" target="_blank" title="INRAE">
                                        	<img style="width: 50%; height: auto;" src="{{ url_for('static', filename='img/inrae-logo.png') }}" alt="INRAE"/>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </footer>
		</div>
	</body>
</html>

app/templates/home.html
{% extends "conteneur.html" %}
{% block head %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css" crossorigin=""/>
<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css" crossorigin=""/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"/>
<link rel="stylesheet" href="{{ url_for('static', filename='css/leaflet.zoomhome.css') }}"/>
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
<script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js" crossorigin=""></script>
<script src="{{ url_for('static', filename='js/leaflet.zoomhome.min.js') }}"></script>
{% endblock %}
{% block corps %}
<div class="margin-page">
 <div class="josefin-sans-text">
    <p>Ce site présente les résultats d'un travail d'édition, d'encodage scientifique et d'analyse des monographies des Ouvriers des deux mondes, réalisé dans le cadre du programme ANR « Time Us ». Les monographies sont des recueils d'enquêtes sociologiques publiés sous l'égide de Frédéric Le Play (†1882) et de la Société internationale des études pratiques d'économie sociale de 1857 à 1913, deux fascicules supplémentaires paraissant en 1930. / <a style="text-decoration: none;" href="{{ url_for('main.about') }}" title="À propos de ce site">En savoir plus</a> / <a style="text-decoration: none;" href="{{ url_for('main.monographies') }}" title="Corpus des monographies">Accéder au corpus</a> / <a style="text-decoration: none;" href="{{ url_for('main.search') }}" title="Recherche">Faire une recherche</a>.</p>
</div>
<div style="margin: 0em auto 0 auto; width: 100%;">
        <div id="my-map"></div>
        <p class="josefin-sans-text">Cette carte situe les terrains d'enquête des monographies. Les deux mondes mentionnés dans le titre&#160;&#8211;&#160;sans doute inspiré par la revue du même nom, fondée en 1829&#160;&#8211; sont les deux rives de l'Atlantique ou de la Méditerranée.</p>
    </div>
</div>
<script>
window.onload = function () {
    var map = L.map('my-map', {
        zoomControl: false,
        tap: false,
    });
    L.tileLayer('https://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> | Localisation des monographies des <i>Ouvriers des deux mondes</i> &copy; <a href="{{ url_for('main.terms') }}">CNRS ETALAB 2.0</a>'
    }).addTo(map);

    var layer = L.markerClusterGroup({
        maxClusterRadius: 50,
        singleMarkerMode: true,
        iconCreateFunction: function (cluster) {
            var childCount = cluster.getChildCount();
            var c = ' marker-cluster-small';
            return new L.DivIcon({ html: '<div><span>' + childCount + '</span></div>', className: 'marker-cluster' + c, iconSize: new L.Point(40, 40) });
        },
    });

{% for mono in corpus %}
    {% if mono.lat %}
    layer.addLayer(
        L.marker([{{ mono.lat }}, {{ mono.lng }}]).bindPopup({{ mono.tooltip() | tojson }}, {minWidth: 400, maxWidth: 400})
    );
    {% endif %}
{% endfor %}

    layer.addTo(map);
    map.fitBounds(layer.getBounds());
    map.addControl(L.Control.zoomHome({
        zoomHomeIcon: 'globe',
        zoomHomeTitle: 'Réinitialier la vue'
    }));
};
</script>
{% endblock %}

app/templates/mono.html
{% extends "conteneur.html" %}
{% block titre %}{# Explicitely disables title #}{% endblock %}
{% block corps %}

{{ content | safe }}
<script>
    $(document).ready(function() {
        $("body").css('margin-bottom', $('#monofooter').outerHeight());
    });
</script>

<nav class="navbar navbar-expand-lg navbar-light bg-white fixed-bottom" id="monofooter">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#monoNavbarContent" aria-controls="monoNavbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="monoNavbarContent">
            <div class="container-fluid">
                <ul class="navbar-nav nav-justified me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        {% if prev %}
                        <a class="nav-link" href="{{ url_for('main.txt_mono', slug=prev.slug) }}">&laquo; N°{{ prev.public_id }} &#8212; {{ prev.short_title }} &laquo;</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        <p class="navbar-text mb-0">
                            <strong>N°{{ monography.public_id }} &#8212; {{ monography.short_title }}</strong><br>
                            <small><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                            <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                            <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                            </svg> <a class="nav-link inline" href="{{ url_for('main.download_xml', slug=monography.slug) }}">XML</a>, <a class="nav-link inline" href="{{ url_for('main.download_pdf', slug=monography.slug) }}">PDF</a></small>
                        </p>
                    </li>
                    <li class="nav-item">
                        {% if next %}
                        <a class="nav-link" href="{{ url_for('main.txt_mono', slug=next.slug) }}">&raquo; N°{{ next.public_id }} &#8212; {{ next.short_title }} &raquo;</a>
                        {% endif %}
                    </li>
                    <li>
                        <p style="font-size: 11px;"><a href="#">Haut de page &#x2191</a></p>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
{% endblock %}

app/templates/results-full.html
{% extends "conteneur.html" %}
{% block corps %}

{% if results.get_object_list() %}
  <div>
    {% for item in results.get_object_list() %}
    <h3><a href="{{url_for('main.txt_mono', slug=item.slug) }}">
      N°{{ item.public_id }} - {{ item.hi_title | safe }}
    </a></h3>
    <div class="container"><blockquote><p>{{ item.hi_content | safe }}</p></blockquote></div>
    <hr>
    {% endfor %}
  </div>

  <nav aria-label="Pages des résultats de la recherche">
    <ul class="pagination pagination-sm justify-content-center">
      <li class="page-item{% if results.get_page() == 1 %} disabled{% endif %}">
        <a class="page-link text-center" href="{{ url_for('main.searchfts', term=term, page=1) }}">Première page</a>
      </li>
      <li class="page-item{% if results.get_page() == 1 %} disabled{% endif %}">
        <a class="page-link text-center" href="{{ url_for('main.searchfts', term=term, page=results.get_page() - 1) }}">
          Page précédente
        </a>
      </li>
      <li class="page-item disabled">
        <span class="page-link text-center">Page {{ results.get_page() }} sur {{ results.get_page_count() }}</span>
      </li>
      <li class="page-item {% if results.get_page() == results.get_page_count() %} disabled{% endif %}">
        <a class="page-link text-center" href="{{ url_for('main.searchfts', term=term, page=results.get_page() + 1) }}">
          Page suivante
        </a>
      </li>
      <li class="page-item {% if results.get_page() == results.get_page_count() %} disabled{% endif %}">
        <a class="page-link text-center" href="{{ url_for('main.searchfts', term=term, page=results.get_page_count()) }}">
          Dernière page
        </a>
      </li>
    </ul>
  </nav>
{% else %}
  <p class="lead">Cette recherche n'a donné aucun résultat.</p>
{% endif %}
{% endblock %}

app/templates/results-simple.html
{% extends "conteneur.html" %}
{% block corps %}

{% if results.get_object_list() %}
  <div>
    {% for item in results.get_object_list() %}
    <h3><a href="{{url_for('main.txt_mono', slug=item.monography.slug, _anchor=type.label + '-' + subtype.label) }}">
      N°{{ item.monography.public_id }} - {{ item.monography.title }}
    </a></h3>
    <div class="container"><blockquote>{{ item.content | safe }}</blockquote></div>
    <hr>
    {% endfor %}
  </div>
  <script>
    $(document).ready(function () {
      $("blockquote").each(function (idx) {
        var paragraphs = $(this).find("p");
        if (paragraphs.length > 5) {
          var hidden_paragraphs = paragraphs.slice(4);  // We select 1 paragraph less to avoid having "Display 1 more"
          hidden_paragraphs.hide();
          $(this).append('<p><button type="button" class="btn btn-outline-secondary">Afficher ' + hidden_paragraphs.length + ' paragraphes supplémentaires</button></p>');
          var btn = $(this).find('button');
          btn.bind('click', function () {
            hidden_paragraphs.slideToggle();
            if (btn.text().startsWith('Afficher')) {
              btn.text('Masquer les ' + hidden_paragraphs.length + ' derniers paragraphes');
            } else {
              btn.text('Afficher ' + hidden_paragraphs.length + ' paragraphes supplémentaires');
            }
          })
        }
      });
    });
  </script>

  <nav aria-label="Pages des résultats de la recherche">
    <ul class="pagination pagination-sm justify-content-center">
      <li class="page-item{% if results.get_page() == 1 %} disabled{% endif %}">
        <a class="page-link text-center" href="{{ url_for('main.results', where=where, term=term, page=1) }}">Première page</a>
      </li>
      <li class="page-item{% if results.get_page() == 1 %} disabled{% endif %}">
        <a class="page-link text-center" href="{{ url_for('main.results', where=where, term=term, page=results.get_page() - 1) }}">
          Page précédente
        </a>
      </li>
      <li class="page-item disabled">
        <span class="page-link text-center">Page {{ results.get_page() }} sur {{ results.get_page_count() }}</span>
      </li>
      <li class="page-item {% if results.get_page() == results.get_page_count() %} disabled{% endif %}">
        <a class="page-link text-center" href="{{ url_for('main.results', where=where, term=term, page=results.get_page() + 1) }}">
          Page suivante
        </a>
      </li>
      <li class="page-item {% if results.get_page() == results.get_page_count() %} disabled{% endif %}">
        <a class="page-link text-center" href="{{ url_for('main.results', where=where, term=term, page=results.get_page_count()) }}">
          Dernière page
        </a>
      </li>
    </ul>
  </nav>
{% else %}
  <p class="lead">Cette recherche n'a donné aucun résultat.</p>
{% endif %}
{% endblock %}